# Generated by Django 4.2.14 on 2024-08-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trs',
            name='acwr',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='trs',
            name='trs_acwr',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
