# Generated by Django 5.0.7 on 2024-07-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='cycle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='cycles.menstrualcycle'),
        ),
    ]
