# Generated by Django 5.0.7 on 2024-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_alter_phase_cycle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='avg_duration',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
