# Generated by Django 5.0.7 on 2024-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='value',
            new_name='strength',
        ),
    ]
