# Generated by Django 5.0.6 on 2024-06-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('phase_number', models.PositiveIntegerField(choices=[(0, 'Menstruation'), (1, 'Follicular'), (2, 'Ovulation'), (3, 'Luteal')])),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menstrualcycle')),
            ],
        ),
    ]
