# Generated by Django 4.2.14 on 2024-07-31 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='cycle_duration',
            field=models.PositiveSmallIntegerField(default=29),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='menstruation_duration',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='workout_duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='workout_frequency',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='workout_intensity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
