# Generated by Django 5.0.7 on 2024-07-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_medicationcategory_symptomcategory_medication_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phase",
            name="cycle_id",
        ),
        migrations.DeleteModel(
            name="MenstrualCycle",
        ),
        migrations.DeleteModel(
            name="Phase",
        ),
    ]
