# Generated by Django 5.0.6 on 2024-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_menstrualcycle_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menstrualcycle',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menstrualcycle',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start',
            field=models.DateField(),
        ),
    ]
