# Generated by Django 5.0.7 on 2024-07-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_phase_cycle_id_delete_menstrualcycle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symptom",
            name="symptom_category",
        ),
        migrations.RemoveField(
            model_name="symptom",
            name="user",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="SymptomCategory",
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
    ]
