# Generated by Django 5.0.7 on 2024-07-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_symptom_symptom_category_remove_symptom_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="medication_id",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="user",
        ),
        migrations.DeleteModel(
            name="MedicationCategory",
        ),
        migrations.DeleteModel(
            name="Medication",
        ),
    ]
