# Generated by Django 5.0.7 on 2024-07-18 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_medication_medication_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('workout_frequency', models.PositiveSmallIntegerField()),
                ('workout_duration', models.PositiveSmallIntegerField()),
                ('workout_intensity', models.PositiveSmallIntegerField()),
                ('cycle_duration', models.PositiveSmallIntegerField()),
                ('menstruation_duration', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
