# Generated by Django 5.0.7 on 2024-07-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_onboarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='finished_onboarding',
            new_name='onboarding_finished',
        ),
    ]
