# Generated by Django 5.0.7 on 2024-07-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contraceptives_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraceptive',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contraceptive',
            name='show_hint',
        ),
    ]
